// Task 2.3 — Terminal Payment (server-driven integration)
// Lab page: Module 2 → Task 2.3
//
// Server-driven: no client SDK. The hotel/restaurant's existing system (PMS/POS)
// calls these routes directly; the S710 reader is driven entirely via the API.

const express = require('express');
const router = express.Router();
const db = require('../db');
const { config } = require('../config');
const { stripe, onAccount, idemKey, describeStripeError } = require('../lib/stripe');
const { logEvent } = require('../lib/events');
const { ensureLocation, cacheReader } = require('../lib/terminal');

function requireMerchantWithAccount(req, res) {
  const merchant = db.merchants.findById(req.body.merchantId || req.query.merchantId);
  if (!merchant) { res.status(404).json({ error: 'Merchant not found' }); return null; }
  if (!merchant.stripe_account_id) { res.status(400).json({ error: 'Merchant has no Stripe account yet' }); return null; }
  return merchant;
}

// POST /terminal/readers/register
// One-time setup: register a physical S710 using the registration code shown on its screen
router.post('/readers/register', async (req, res) => {
  const merchant = requireMerchantWithAccount(req, res);
  if (!merchant) return;
  const { registrationCode, label } = req.body;

  try {
    const locationId = await ensureLocation(merchant);
    const reader = await stripe.terminal.readers.create(
      { registration_code: registrationCode, label: label || 'Reader', location: locationId },
      onAccount(merchant),
    );

    cacheReader(merchant, reader, label);
    logEvent({
      merchantId: merchant.id,
      kind: 'terminal.reader.registered',
      message: `Reader ${reader.label || reader.id} registered to ${merchant.name}`,
      payload: { readerId: reader.id, deviceType: reader.device_type, locationId },
    });

    res.json({ readerId: reader.id, status: reader.status, deviceType: reader.device_type });
  } catch (err) {
    console.error('Reader registration failed:', describeStripeError(err));
    res.status(400).json(describeStripeError(err));
  }
});

// GET /terminal/readers
// List readers registered to a merchant's connected account
router.get('/readers', async (req, res) => {
  const merchant = requireMerchantWithAccount(req, res);
  if (!merchant) return;

  try {
    const readers = await stripe.terminal.readers.list({ limit: 20 }, onAccount(merchant));
    res.json({
      readers: readers.data.map(r => ({
        id: r.id,
        label: r.label,
        status: r.status,
        deviceType: r.device_type,
        kind: (r.device_type || '').startsWith('simulated') ? 'simulated' : 'physical',
      })),
    });
  } catch (err) {
    res.status(400).json(describeStripeError(err));
  }
});

// POST /terminal/payment-intent
// Create a direct-charge PaymentIntent on the connected account for a card-present Terminal payment.
//
// Extension (pre-auth / "Open bar tab"): passing manualCapture: true holds the auth
// instead of charging immediately, and marks the card reusable off-session later —
// same PaymentIntent, same reader flow, just capture_method + setup_future_usage.
router.post('/payment-intent', async (req, res) => {
  const merchant = requireMerchantWithAccount(req, res);
  if (!merchant) return;
  const { amount, manualCapture } = req.body;

  try {
    // TODO: Create a card_present PaymentIntent as a direct charge on the connected
    // account, with the platform's application fee (2.5% of amount). When
    // manualCapture is true, use capture_method: 'manual' and set
    // setup_future_usage: 'off_session' so the card can be reused later.
    // Respond with { paymentIntentId }.
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

// POST /terminal/payment-intent/:id/capture
// Extension: capture a pre-authorized PaymentIntent for the final amount (may be less than the hold)
router.post('/payment-intent/:id/capture', async (req, res) => {
  const merchant = requireMerchantWithAccount(req, res);
  if (!merchant) return;
  const { amount } = req.body;

  try {
    // TODO: Capture the PaymentIntent for amount_to_capture: amount. Respond with
    // { status, amountCaptured }.
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

// GET /terminal/payment-intent/:id/saved-card
// Extension: read the reusable card generated by a manualCapture payment, once the reader has confirmed it
router.get('/payment-intent/:id/saved-card', async (req, res) => {
  const merchant = requireMerchantWithAccount(req, res);
  if (!merchant) return;

  try {
    // TODO: Retrieve the PaymentIntent, expanding latest_charge, and read the
    // generated card id off payment_method_details.card_present.generated_card.
    // If it's not there yet, respond with a 400 error. Otherwise respond with
    // { savedPaymentMethodId }.
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

// POST /terminal/off-session-charge
// Extension: charge a previously-saved card without the guest present — no Customer
// object required, the raw PaymentMethod id from saved-card above is enough.
router.post('/off-session-charge', async (req, res) => {
  const merchant = requireMerchantWithAccount(req, res);
  if (!merchant) return;
  const { amount, paymentMethodId, description } = req.body;

  try {
    // TODO: Create and confirm a new PaymentIntent off-session using paymentMethodId,
    // with off_session: true, confirm: true, and the platform's application fee.
    // Respond with { paymentIntentId, status }.
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

// GET /terminal/payment-intent/:id/status
// Poll a PaymentIntent's status after pushing it to a reader
router.get('/payment-intent/:id/status', async (req, res) => {
  const merchant = requireMerchantWithAccount(req, res);
  if (!merchant) return;

  try {
    // TODO: Retrieve the PaymentIntent and respond with { status, amount }.
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

// POST /terminal/process
// Push a PaymentIntent to a specific reader — the guest taps/inserts their card on the S710.
// allowRedisplay is optional — only needed when the PaymentIntent has setup_future_usage set
// (e.g. POS's "Open bar tab" pre-auth, which saves the card for later incidentals).
router.post('/process', async (req, res) => {
  const merchant = requireMerchantWithAccount(req, res);
  if (!merchant) return;
  const { readerId, paymentIntentId, allowRedisplay } = req.body;

  try {
    // TODO: Push paymentIntentId to readerId (processPaymentIntent). When
    // allowRedisplay is provided, pass it through as process_config.allow_redisplay.
    // Respond with { readerId, action }.
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

// POST /terminal/simulate-card
// Test-mode only: simulates a card tap on a simulated reader
router.post('/simulate-card', async (req, res) => {
  const merchant = requireMerchantWithAccount(req, res);
  if (!merchant) return;
  const { readerId } = req.body;

  try {
    // TODO: Simulate a card tap on readerId using the test_helpers
    // presentPaymentMethod endpoint. Respond with { readerId, action }.
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

module.exports = router;
